// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC186LFvNq6vSOXdhgxiafKBmjg248Aho0',
    appId: '1:682179914707:web:14fcbf038c3452e2465d26',
    messagingSenderId: '682179914707',
    projectId: 'chad-chat-19068',
    authDomain: 'chad-chat-19068.firebaseapp.com',
    storageBucket: 'chad-chat-19068.appspot.com',
    measurementId: 'G-VT4B5LQ93T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtAZRppbgJYVcZ8Cud-VeqR0YtapEJVgI',
    appId: '1:682179914707:android:d7cab4f5e3174225465d26',
    messagingSenderId: '682179914707',
    projectId: 'chad-chat-19068',
    storageBucket: 'chad-chat-19068.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPKFks9PsEljwQhl6kEYKJpqB66jzyCto',
    appId: '1:682179914707:ios:4e6d3afa15871529465d26',
    messagingSenderId: '682179914707',
    projectId: 'chad-chat-19068',
    storageBucket: 'chad-chat-19068.appspot.com',
    iosBundleId: 'com.example.chadChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPKFks9PsEljwQhl6kEYKJpqB66jzyCto',
    appId: '1:682179914707:ios:4e6d3afa15871529465d26',
    messagingSenderId: '682179914707',
    projectId: 'chad-chat-19068',
    storageBucket: 'chad-chat-19068.appspot.com',
    iosBundleId: 'com.example.chadChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC186LFvNq6vSOXdhgxiafKBmjg248Aho0',
    appId: '1:682179914707:web:6b8e0694401920d3465d26',
    messagingSenderId: '682179914707',
    projectId: 'chad-chat-19068',
    authDomain: 'chad-chat-19068.firebaseapp.com',
    storageBucket: 'chad-chat-19068.appspot.com',
    measurementId: 'G-H5750ZZKSL',
  );
}
